FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache libc6-compat
COPY package.json turbo.json ./
COPY packages/shared-types/package.json ./packages/shared-types/
COPY apps/backend/package.json ./apps/backend/
RUN npm install
COPY . .
EXPOSE 3001
CMD ["npm", "run", "dev", "--workspace=apps/backend"]
